### PR TITLE
Migrate to Go modules

### PR DESCRIPTION
**Pull request by gen2brain**
Migrate to Go modules so go build can just works.

### CODE REVIEW

**Comment by anguenot** [comment]
@gen2brain  can you fix the conflicts on `travis.yaml` as I pushed an update for the test matrix?

**Comment by gen2brain** [comment]
Ok, should be good now.

**Comment by anguenot** [comment]
@gen2brain  you can check the status of the builds against your branch here: https://travis-ci.org/github/anguenot/ipfix-forwarder/builds/729432018

**Comment by anguenot** [comment]
@gen2brain  note, if we only want to support newer versions of Golang this is fine. Just amend the commit with the information on supported version.

**Comment by gen2brain** [comment]
Changed, it can be built also for 1.11 and 1.12, with GO111MODULE.

**Review by anguenot — APPROVED** [review]

**Pull request merged**
